apiVersion: v1
kind: Pod
metadata:
  name: query
spec:
  containers:
  - image: kevin7674/device-query:latest
    name: query
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: "3Gi"
      requests:
        cpu: 50m
        memory: 50Mi
        ephemeral-storage: "2Gi"
